#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)
repo_name=$(basename "$(git rev-parse --show-toplevel)")

if [[ "$branch" == "main" || "$branch" == "master" ]]; then
    echo "⚠️  You are pushing to '$branch' in repository '$repo_name'."
    echo -n "Are you sure? (y/n): " > /dev/tty
    read confirm < /dev/tty
    if [[ "$confirm" != "y" ]]; then
        echo "🚫 Push aborted."
        exit 1
    fi
fi
